# YAML linting configuration
extends: default

rules:
  line-length:
    max: 120
    level: warning

  indentation:
    spaces: 2
    indent-sequences: true

  comments:
    min-spaces-from-content: 1

  # Allow duplicate keys (common in Copilot manifests with overrides)
  key-duplicates: disable

  # Allow documents to start without ---
  document-start: disable

  # Allow truthy values like "on", "yes" which are common in config files
  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']
